<?php

namespace BreezyBeasts\AuroraDsql\Schema;


class Blueprint extends \Illuminate\Database\Schema\Blueprint
{
    protected array $primaryKeys = [];
    protected array $uniqueKeys = [];

    public function asyncIndex($columns, $indexName = null)
    {
        $indexName = $indexName ?: $this->createIndexName('index', (array) $columns);
        return $this->addCommand('asyncIndex', [
            'columns' => (array) $columns,
            'ifNotExists' => false,
            'unique' => false,
            'indexName' => $indexName,
            'includedColumns' => [],
            'nullsPosition' => null,
        ]);


    }

    protected function addCommand($name, array $parameters = [])
    {
        if($name == 'asyncIndex') {
            $command = new AsyncIndexCommand(array_merge(compact('name'), $parameters));

            $this->commands[] = $command;

            return $command;
        }
        return parent::addCommand($name, $parameters); // TODO: Change the autogenerated stub
    }

    public function primary($columns = null, $name = null, $algorithm = null): static
    {
        $columns = (array) $columns;

        // Track primary keys for compilation into CREATE TABLE
        $this->primaryKeys = array_merge($this->primaryKeys, $columns);

        return $this;
    }

    public function getPrimaryKeys(): array
    {
        return $this->primaryKeys;
    }

    public function unique($columns, $name = null, $algorithm = null): static
    {
        $columns = (array) $columns;

        // Track unique keys for compilation into CREATE TABLE
        $this->uniqueKeys[] = [
            'columns' => $columns,
            'name' => $name,
        ];

        return $this;
    }

    public function getUniqueKeys(): array
    {
        return $this->uniqueKeys;
    }
}
